# [security]
# Limit users accepted with email from this domain
# allowed-domain = "yourdomain.com"
#
# Secret used to protect the JWT used after authentication.
# secret = "<SOME RANDOME SECRET STRING>"
#
# Administration function are enabled for users with these emails
# admin-emails = ["you@yourdomain.com"]

# [oauth.google]
# Create the your oauth application from the API developer console
# see: https://developers.google.com/identity/protocols/oauth2/web-server
#
# When setting it up the callback URL will be:
#    https://domain.from.config.below/auth/callback/google
#
# client-id = "LONG_RAND_STRING.apps.googleusercontent.com"
# client-secret = "GOCSPX-LONG_RANDOM_STRING"

# [web]
# Set the publicly visible domain name for the web server
# Defaults to IP from LAN
# domain = "fringe.mydomain.com"
#
# Automatically get TLS server certification using https://letsencrypt.org
# Defaults to yes if a domain (not an IP) is set.
# lets-encrypt = true

# [storage]
# Change the default locations for information storage.
# Usually you should not need to change this
#
# User database file location
# user-database = "/var/lib/fringe/fringe.db"
#
# Secrets key file location (where the Radius secret is located)
# secrets-file = "/var/lib/fringe/secrets.json"

# [services]
# Set where fringe listen for each of its services.
# You would only need to change this if it conflicts with other services
# or if you wish to host it behind a reverse proxy
#
# http-bind-address = ":80"
# https-bind-address = ":443"
# radius-bind-address = ":1812"